---
version: 2
multicolumn: false
web-width: '1000'
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/Network-01/Network-01.png
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    url: "/users/75497/articles/196728/master/file/figures/Network-01/Network-01.png"
    folder_url: "/users/75497/articles/196728/master/folder/figures/Network-01"
